---
title: Research output
---

## Publications

### Journal articles (refereed)

**Goldshtein, Yonatan** & Liv Moeslund Ahlgreen. 2021. Ideologies of language and place: conflicting expectations to dialectal speech between informants and dialectologists. *Journal of Postcolonial Linguistics* 5: 178-203. [open access](https://iacpl.net/jopol/issues/journal-of-postcolonial-linguistics-52021/ideologies-of-language-and-place/){target="_blank"}

Hansen, Inger Schoonderbeek & **Yonatan Goldshtein**. 2021. Popular geopolitics and the conceptualization of linguistic norm centres, *Journal of Postcolonial Linguistics* (5): 204-225. [open access](https://iacpl.net/jopol/issues/journal-of-postcolonial-linguistics-52021/popular-geopolitics-and-the-conceptualization-of-linguistic-norm-centres/){target="_blank}

Sabonytė, Regina & **Yonatan Goldshtein**. 2021. F0 and duration changes in unstressed vs stressed syllables connected to postlexical stress and sentence type in Standard Lithuanian. *Nordlyd* (45):119-228 [open access](https://septentrio.uit.no/index.php/nordlyd/article/view/6248/6395){target="_blank}

### Chapters in edited volumes

Bakker, Peter, Kristoffer Friis Bøegh & **Yonatan Goldshtein**. 2021. The languages of Edelberg’s Nuristan and environs. In Ulrik Høj Johnsen, Schluyer Jones, Torkil Funder & Taj Khan Kalash (eds.) *Toward the horizon: Edelberg and the Danish Hindukush research*, 69-87. Aarhus: Aarhus University Press

**Goldshtein, Yonatan**. 2017. The simple emerging from the complex: Nominal number in Juba Arabic creole. In Peter Bakker, Finn Borchsenius, Carsten Levise & Eeva Sippola (eds). *Creole studies: phylogenetic approaches*, 193-217. Amsterdam: John Benjamins Publishing Company. [open access](https://doi.org/10.1075/z.211.09gol){target="_blank}

Levisen, Carsten, Carol Priestly, Sophie Nicholls & **Yonatan Goldshtein**. 2017. The Semantics of Englishes and Creoles: Australian and Melanesian perspectives. In Peter Bakker, Finn Borchsenius, Carsten Levise & Eeva Sippola (eds). *Creole studies: phylogenetic approaches*, 345-368. Amsterdam: John Benjamins Publishing Company [open access](https://doi.org/10.1075/z.211.15lev){target="_blank}

### Articles in conference proceedings

Ahlgreen, Liv Moeslund & **Yonatan Goldshtein**. 2021. Hows nu det jysk! Når dialektinformanten ikke taler jysk nok.In Goldshtein, Yonatan, Tina Thode Hougaard & Inger Schoonderbeek Hansen (eds.) *18. møde om Udforskningen af Dansk Sprog*, 27-40 [pdf](ahlgreen_goldshtein_2021_hows.pdf) | [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds18_2_.pdf){target="_blank}

**Goldshtein, Yonatan**. 2021. Stødets naturlige historie. In Goldshtein, Yonatan, Tina Thode Hougaard & Inger Schoonderbeek Hansen (eds.) *18. møde om Udforskningen af Dansk Sprog*, 151-172 [pdf](goldshtein_2021_stødets.pdf) | [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds18_2_.pdf){target="_blank}

Hansen, Inger Schoonderbeek & **Yonatan Goldshtein**. 2021. Er København (virkelig) eneste sproglige normcenter? In Goldshtein, Yonatan, Tina Thode Hougaard & Inger Schoonderbeek Hansen (eds.) *18. møde om Udforskningen af Dansk Sprog*, 189-210 [pdf](hansen_goldshtein_2021_københavnsk.pdf)  |  [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds18_2_.pdf){target="_blank}

**Goldshtein, Yonatan**. 2019. Sidder, går og står og…: et interaktionelt blik på kongruenskonstruktion i dansk. In Goldshtein, Yonatan, Tina Thode Hougaard & Inger Schoonderbeek Hansen (eds.) *17. møde om Udforskningen af Dansk Sprog*, 277-292 [pdf](goldshtein_2019_kongruenskonstruktion.pdf) | [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds_17.pdf){target="_blank}

### Edited volumes

**Goldshtein, Yonatan**, Tina Thode Hougaard & Inger Schoonderbeek Hansen. 2021. *18. Møde om udforskningen af dansk sprog*. Aarhus University [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds18_2_.pdf){target="_blank}

**Goldshtein, Yonatan**, Tina Thode Hougaard & Inger Schoonderbeek Hansen. 2019. *17. Møde om udforskningen af dansk sprog*. Aarhus University [open access](LINK){target="_blank} [full volume](https://projekter.au.dk/fileadmin/projekter/Muds.dk/rapporter/Muds_17.pdf){target="_blank}

### Reviews

Willemsen, Jeroen & **Yonatan Goldshtein**. 2020. Review of LexiRuma 3.0.0, *Language Documentation & Conservation* 14, 692-702 [open access](http://hdl.handle.net/10125/24969){target="_blank}


### Journal articles (non-refereed)

**Goldshtein, Yonatan**. 2020. Hvordan opstod stødet? *Ord & Sag* 40, 4-13 [pdf](goldshtein_2020_hvordan.pdf) | [full volume](ordsag40.pdf)

**Goldshtein, Yonatan** & Rasmus Puggaard. 2019. Overblik over danske dialektoptagelser. *Ord & Sag* 39, 18-28  [pdf](goldshtein_puggaard_2019_overblik.pdf) | [full volume](ordsag39.pdf)


### Dissertation
**Goldshtein, Yonatan**. 2023. *Outline of a prosodic theory of stød*. PhD Thesis. Aarhus University 

## Presentations

### Conference and workshop presentations

**Goldshtein, Yonatan**. 2024 "Stød in Danish Compounds". *NoWPhoMo: Nominal Inflection and Word-Formation at the Phonology-morphology Interface*, January 25--26, University of Barcelona & Autonomous University of Barcelona

**Goldshtein, Yonatan** & Pavel Iosad. 2024. "The Moraic Mess that is Danish", *FiNo: Fonologi i Norden*, February 23--24, Stockholm University

**Goldshtein, Yonatan**. 2022. "Outline of a prosodic theory of stød". *Prosody in North Germanic Languages*, November 24--25, Lund University

**Goldshtein, Yonatan** & Pavel Iosad. 2022. "Metrical structure and Stratal Phonology provide a complete account of Danish stød". *Manchester Phonology Meeting*, May 25--27, University of Manchester 

**Goldshtein, Yonatan** & Miguel Vazquéz-Larruscaín. 2022. "Danish stød in paroxytones is sensitive to the sonority of the post-tonic syllable", *Fonologi i Norden*, January 13--14, Aarhus University

**Goldshtein, Yonatan**. 2021. "Tone alone is not enough - on the origin of stød". *Workshop in prosodic variation and change in Danish*, December 15--16, Aarhus University 

**Goldshtein, Yonatan**. 2021. "Rekonstruktion af prosodiske forhold". *Workshop om ømål og østdanske dialekter*, June 17--18, University of Copenhagen 

Ahlgreen, Liv Moeslund & **Yonatan Goldshtein**. 2020. "Sprog-sted-forbindelsen problematiseret gennem ældre, stedsstabile talere". *18. Møde om Udforskningen af Dansk Sprog*, October 8--9, Aarhus University

Hansen, Inger Schoonderbeek & **Yonatan Goldshtein**. 2020. "Er København (virkelig) eneste sproglige normcenter?". *18. Møde om Udforskningen af Dansk Sprog*, October 8--9, Aarhus University

**Goldshtein, Yonatan**. 2020. "Bidrag til stødets naturhistorie". *18. Møde om Udforskningen af Dansk Sprog*, October 8--9, Aarhus University

**Goldshtein, Yonatan**. 2020. "Stød models and the Jutlandic dialects of Danish". *Fonologi i Norden*. February 21--22, University of South-Eastern Norway 

Puggaard, Rasmus & **Yonatan Goldshtein**. 2020. "Realization and representation of plosives in Jutlandic varieties of Danish. Variation in phonetics predicts variation in phonology". *Laboratory Phonology*, July 6--8, University of British Columbia & Simon Fraser University. [Video](https://www.youtube.com/watch?v=u8ZVkTOBzt4)

**Goldshtein, Yonatan**. 2019. "Tonal accent in Felsted, Southern Jutland". *ICLaVE|10: International Conference on Language Variation in Europe*, June 26--28, Fryske Akademy 


**Goldshtein, Yonatan**. 2018. "Sidder, går og står og…: et interaktionelt blik på kongruenskonstruktion i dansk". *17. Møde om Udforskningen af Dansk Sprog*. October 11--12, Aarhus University

**Goldshtein, Yonatan**. 2018. "Where is 'it' - Phonetic reduction of the clitic pronoun -ə in Himmerlandsk". *Phonetics and Phonology in Denmark*, August 18, Aarhus University 

**Goldshtein, Yonatan**. 2015. "The simple emerging from the complex: a case study in nominal number marking in Juba Arabic Creole". *Society for Pidgin and Creole Linguistics/ Association of Portuguese and Spanish-Lexified Creoles joint meeting*, July 7--9 University of Graz

### Posters

Puggaard, Radmus & **Yonatan Goldshtein**. 2019. "Large-scale corpus-based analysis of regional varieties of Danish". *ICLaVE|10: International Conference on Language Variation in Europe*, June 26--28, Fryske Akademy 

### Inivted talks

**Goldshtein, Yonatan**. 2024. "Sprogholdningsparadoksets struktur". Peter Skautrup Centret for Jysk Dialektforskning, April 9, Aarhus Universitet 

**Goldshtein, Yonatan** 2023. "Dansk fonologis hovedproblem og hvordan vi løser det – en ny teori om det danske stød". Lingvistkredsen, October 30, University of Copenhagen

**Goldshtein, Yonatan** 2023. "Sprogholdningsparadoksets struktur". Sociolingvistisk Studiekreds, October 31, University of Copenhagen 


### Departmental talks

*Work in progress* 